# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matriks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rmatriks.proto\x12\tdepthfeed"D\n\nOrderLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0b\n\x03qty\x18\x02 \x01(\x04\x12\n\n\x02ts\x18\x03 \x01(\x04\x12\x0e\n\x06orders\x18\x04 \x01(\r"\x93\x01\n\rDepthSnapshot\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x13\n\x0bsession_tag\x18\x02 \x01(\t\x12\x13\n\x0bsnapshot_ts\x18\x03 \x01(\x04\x12#\n\x04\x61sks\x18\x04 \x03(\x0b\x32\x15.depthfeed.OrderLevel\x12#\n\x04\x62ids\x18\x05 \x03(\x0b\x32\x15.depthfeed.OrderLevelb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "matriks_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ORDERLEVEL._serialized_start = 28
    _ORDERLEVEL._serialized_end = 96
    _DEPTHSNAPSHOT._serialized_start = 99
    _DEPTHSNAPSHOT._serialized_end = 246
# @@protoc_insertion_point(module_scope)
